### ISSUE TITLE
plot a transcript with all transcripts as background

### ISSUE THREAD

**Issue by xiaonalu** [mortazavilab/swan_vis#17]
Hello,
I want to ask for a further skill on how to keep all the transcripts as background when I only plot a transcript. I tried plot the gene first, then plot a transcript, the figure shows mix figures, rather the gene as light background in the tutorial. If I only plot the transcript, after read the swan.p in, I cannot see the other transcripts in my plot. Thanks

**Comment by fairliereese** [comment]
Is [this](https://freese.gitbook.io/swan/tutorials/visualization#transcript-path-graphs) the sort of plot you're trying to make? Can you send me a screenshot of your output? Thanks!

**Comment by xiaonalu** [comment]
Yes, exactly~ However, when I want to have other transcripts as background for one of my transcript, it looks as the second fig. Thank you
![image](https://user-images.githubusercontent.com/89666046/145658261-b386395d-ff06-44c3-8c24-088fec1b24af.png)

**Comment by fairliereese** [comment]
Whoa, yeah this doesn't look correct. Can you please send me the code you used starting from loading your SwanGraph up through the call that you made to produce the weird figure? Additionally, could you please tell me how and when you installed Swan?

As a side note, Swan has some "clever" code to try and prevent from having to recompute the plotted representation of a gene for which (as you've found out) not all cases are accounted for. A workaround that commonly fixes this in my experience is just reloading the SwanGraph and remaking the plot that's giving you trouble.

**Comment by xiaonalu** [comment]
Hi, here is the code. 
import swan_vis as swan
sg = swan.read('swan.p')
cmap = {'exon': '#003476'}
sg.set_plotting_colors(cmap)
sg.plot_graph('full_gene', indicate_novel=True) 
sg.plot_transcript_path('PB.13560.539', indicate_novel=True)
swan.save_fig('figures/PB.13560.539.png')

I installed the swan around 2 months ago I think. I load miniconda module first, create conda environment, activate conda environment, then install swan_vis with pip... It's a sever at school...

**Comment by fairliereese** [comment]
One more question -- is 'full_gene' the gene that 'PB.13560.539' is from?

**Comment by xiaonalu** [comment]
Hi, there are multiple transcripts of the 'full_gene', it's a single gene. 'PB.13560.539' is one of the transcripts. Thank you very much

**Comment by fairliereese** [comment]
I was unfortunately not able to reproduce your problem. However I did encounter some difficulty using Swan's `save_fig` function where I was getting blank figures. I was able to solve this by calling `save_fig` in the same Jupyter notebook cell as the plot that was produced (see [this post](https://stackoverflow.com/questions/9012487/matplotlib-pyplot-savefig-outputs-blank-image) where there is a comment mentioning that that's the case. Because of this I wanted to ask -- are you running Swan from a Python notebook? The command line? A script? 

Additionally, I wanted to ask you to try providing the `prefix` argument to `plot_transcript_path`. This strategy should automatically generate a file name for your figure and save it which circumvents some of the issues I encountered using iPython notebooks. Please let me know if this works for you!

**Comment by xiaonalu** [comment]
I use a small script as below, then sbatch it.

module load miniconda
conda activate swan
python Swan_visualization.py

In the Swan_visualization.py, I use swan.save_fig('figures/PB.13560.539.png') to save the figure. 

I will try the prefix. Thank you so much, and good night
